#!/usr/bin/env python3

import sys
import argparse
import re
import urllib.parse
from geomet import wkt as wkt_parser
import itertools
from pandas.core.common import flatten


def parse_bbox(line, frmt):
    line = line.strip()
    if frmt == 'URL':
        line = urllib.parse.unquote(line)
        match = re.search(r'BBOX=(\d+\.?\d+,\d+\.?\d+,\d+\.?\d+,\d+\.?\d+)', line, flags=re.IGNORECASE)
        if match:
            line = match.group(1)
    return line.strip().split(',')


def bbox2wkt(bbox):
    x1, y1, x2, y2 = bbox
    wkt = f'POLYGON(({x1} {y1}, {x1} {y2}, {x2} {y2}, {x2} {y1}, {x1} {y1}))'
    return wkt


def wkt2bbox(wkt):
    geom = wkt_parser.loads(wkt.upper())
    # TODO support LineString, MultiLineString, MultiPolygon geometries
    # print(list(itertools.chain.from_iterable(geom['coordinates'])))
    # print(list(flatten(geom['coordinates'])))
    negInf = float("-inf")
    posInf = float("inf")
    xmin, ymin, xmax, ymax = [None, None, None, None]
    # print(geom['coordinates'])
    for ring in geom['coordinates']:
        # print(ring)
        for [x, y] in ring:
            if xmin is None or x < xmin:
                xmin = x
            if xmax is None or x > xmax:
                xmax = x
            if ymin is None or y < ymin:
                ymin = y
            if ymax is None or y > ymax:
                ymax = y
    return f'{xmin},{ymin},{xmax},{ymax}'


def cli():
    desc = "Transform WMS GetMap style BBOX value to WKT or WKT to BBOX"
    arg_parser = argparse.ArgumentParser(__file__, description=desc, argument_default=argparse.SUPPRESS)
    arg_parser.add_argument('--file', help='File containing BBOX or WKT values to convert, if no file is specified the BBOX or WKT is read from stdin')
    arg_parser.add_argument('--format', default="BBOX", help='Format being parsed, either BBOX (default), URL or WKT')
    args = vars(arg_parser.parse_args())
    format = args['format']
    with open(args['file']) if 'file' in args else sys.stdin as f:
        for num, line in enumerate(f, 1):
            if format in ['BBOX', 'URL']:
                try:
                    bbox = parse_bbox(line, format)
                    wkt = bbox2wkt(bbox)
                    print(wkt)
                except Exception as ex:
                    raise ValueError(f'Unable to parse BBOX, line: {num}, text: {line}') from ex
            elif format == 'WKT':
                try:
                    bbox = wkt2bbox(line)
                    print(bbox)
                except Exception as ex:
                    raise ValueError(f'Unable to parse WKT, line: {num}, text: {line}') from ex


if __name__ == '__main__':
    cli()
