#!/usr/bin/python

import argparse
from lxml import etree
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)

if __name__ == '__main__':
    desc = "Apply the specifed xsl file to the xml file and print out the results"
    arg_parser = argparse.ArgumentParser(__file__, description=desc, argument_default=argparse.SUPPRESS)
    arg_parser.add_argument('xsl_file', help='XSLT v1 file to apply to XML file')
    arg_parser.add_argument('xml_file', help='XML file to transform')
    args = arg_parser.parse_args()

    try:
        xsl_file = args.xsl_file
        xml_file = args.xml_file
    except KeyError:
        print(__doc__)
        exit(1)

    xsl_doc = etree.XSLT(etree.parse(open(xsl_file, 'r')))
    xml_doc = etree.parse(open(xml_file, 'r'))
    result = xsl_doc(xml_doc)
    s = etree.tostring(result, encoding='UTF-8', pretty_print=True)
    s = unicode(result) if s is None else s
    print(s)
